---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: dash-ingress
  namespace: osfx
spec:
  rules:
    - host: dashboard.osfx.staging
      http:
        paths:
          - backend:
              serviceName: osfx-page
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: tmc-ingress
  namespace: osfx
spec:
  rules:
    - host: iso.osfx.staging
      http:
        paths:
          - backend:
              serviceName: osfx-tmc
              servicePort: 5010
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: auth-ingress
  namespace: osfx
spec:
  rules:
    - host: auth.osfx.staging
      http:
        paths:
          - backend:
              serviceName: osfx-auth
              servicePort: 5020
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: 'nginx'
  name: user-ingress
  namespace: osfx
spec:
  rules:
    - host: user.osfx.staging
      http:
        paths:
          - backend:
              serviceName: osfx-user
              servicePort: 5021
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: 'nginx'
  name: data-ingress
  namespace: osfx
spec:
  rules:
    - host: data.osfx.staging
      http:
        paths:
          - backend:
              serviceName: osfx-data
              servicePort: 5030
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: 'nginx'
  name: card-ingress
  namespace: osfx
spec:
  rules:
    - host: card.osfx.staging
      http:
        paths:
          - backend:
              serviceName: osfx-card
              servicePort: 5040
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: osfx
data:
  5000: 'osfx/osfx-tmc:5010'
