---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: osfx-ingress
  namespace: osfx
spec:
  rules:
    - http:
        paths:
          - path: /(.+)
            backend:
              serviceName: osfx-page
              servicePort: 5000
    - http:
        paths:
          - path: /tmc/(.+)
            backend:
              serviceName: osfx-tmc
              servicePort: 5010
    - http:
        paths:
          - path: /auto/(.+)
            backend:
              serviceName: osfx-auto
              servicePort: 5011
    - http:
        paths:
          - path: /auth/(.+)
            backend:
              serviceName: osfx-auth
              servicePort: 5020
    - http:
        paths:
          - path: /user/(.+)
            backend:
              serviceName: osfx-user
              servicePort: 5021
    - http:
        paths:
          - path: /data/(.+)
            backend:
              serviceName: osfx-data
              servicePort: 5030
    - http:
        paths:
          - path: /card/(.+)
            backend:
              serviceName: osfx-card
              servicePort: 5040

    - host: dashboard.osfx.staging
      http:
        paths:
          - backend:
              serviceName: osfx-page
              servicePort: 5000
    - host: iso.osfx.staging
      http:
        paths:
          - backend:
              serviceName: osfx-tmc
              servicePort: 5010
    - host: auth.osfx.staging
      http:
        paths:
          - backend:
              serviceName: osfx-auth
              servicePort: 5020
    - host: user.osfx.staging
      http:
        paths:
          - backend:
              serviceName: osfx-user
              servicePort: 5021
    - host: data.osfx.staging
      http:
        paths:
          - backend:
              serviceName: osfx-data
              servicePort: 5030
    - host: card.osfx.staging
      http:
        paths:
          - backend:
              serviceName: osfx-card
              servicePort: 5040
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: osfx
data:
  5000: 'osfx/osfx-tmc:5010'
