apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osfx-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: osfx-mysql
spec:
  selector:
    matchLabels:
      app: osfx-mysql
  serviceName: "osfx-mysql"
  replicas: 2
  template:
    metadata:
      labels:
        app: osfx-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.6
        args:
          - "--ignore-db-dir=lost+found"          
        livenessProbe:
          exec:
            command: ["mysqladmin", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        ports:
        - containerPort: 3306
          name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: R00t
          - name: DISCOVERY_SERVICE
            value: etcd:2379
          - name: XTRABACKUP_PASSWORD
            value: R00t
        ports:
        - name: mysql-port
          containerPort: 3306
          protocol: TCP
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: osfx-msql
  name: osfx-mysql
spec:
  ports:
    - protocol: "TCP"
      port: 3306
      targetPort: 3306
  selector:
    app: osfx-mysql
  clusterIP: "None"
  type: ClusterIP
